version: '3.9'

services:
  
  db:
    container_name: todos.db
    image: postgres:latest
    restart: always
    ports:
      - '5444:5432'
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=changeme
   